=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::CountryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CountryApi' do
  before do
    # run before each test
    @instance = SwiftApi::CountryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CountryApi' do
    it 'should create an instance of CountryApi' do
      expect(@instance).to be_instance_of(SwiftApi::CountryApi)
    end
  end

  # unit tests for country_get
  # Gets all countries.
  # 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [Array<Country>]
  describe 'country_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
