=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::FamilyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FamilyApi' do
  before do
    # run before each test
    @instance = SwiftApi::FamilyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FamilyApi' do
    it 'should create an instance of FamilyApi' do
      expect(@instance).to be_instance_of(SwiftApi::FamilyApi)
    end
  end

  # unit tests for family_get
  # Gets all product families.
  # 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :web_families_only A value indicating whether only web families should be returned.
  # @return [Array<Family>]
  describe 'family_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
