=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::LocationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LocationApi' do
  before do
    # run before each test
    @instance = SwiftApi::LocationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocationApi' do
    it 'should create an instance of LocationApi' do
      expect(@instance).to be_instance_of(SwiftApi::LocationApi)
    end
  end

  # unit tests for location_get
  # Gets all locations.
  # 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [Array<Location>]
  describe 'location_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for location_get_0
  # Gets a location by id.
  # 
  # @param id The id of the location.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [Location]
  describe 'location_get_0 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
