=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::NotificationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NotificationApi' do
  before do
    # run before each test
    @instance = SwiftApi::NotificationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationApi' do
    it 'should create an instance of NotificationApi' do
      expect(@instance).to be_instance_of(SwiftApi::NotificationApi)
    end
  end

  # unit tests for notification_put_device
  # Assigns a device id to a member.
  # 
  # @param id The member id.
  # @param device_id The device id.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :member_type The type of member.
  # @return [nil]
  describe 'notification_put_device test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
