=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::OrderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrderApi' do
  before do
    # run before each test
    @instance = SwiftApi::OrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderApi' do
    it 'should create an instance of OrderApi' do
      expect(@instance).to be_instance_of(SwiftApi::OrderApi)
    end
  end

  # unit tests for order_post
  # Creates a web order.
  # Creates a web order which is sent to SwiftPOS Touch.  When creating a web order, the Id property should be set to reflect your own unique order number.  Orders can be created that have been partially or fully pre-paid or that require full payment at the POS.
  # @param order The order to create.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'order_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
