=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::ProductApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductApi' do
  before do
    # run before each test
    @instance = SwiftApi::ProductApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductApi' do
    it 'should create an instance of ProductApi' do
      expect(@instance).to be_instance_of(SwiftApi::ProductApi)
    end
  end

  # unit tests for product_get
  # Gets all products matching the specified search value.
  # 
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description The product description to search for.
  # @option opts [Integer] :category_id The category id to search for.
  # @option opts [Integer] :family_id The family id to search for.
  # @option opts [Integer] :group_id The group id to search for.
  # @option opts [BOOLEAN] :include_image A value indicating if the response should include product images.
  # @option opts [String] :member_id A member id used to effect the price of the returned product/s.
  # @option opts [Integer] :member_type The type of member search to perform (0 &#x3D; Standard, 3 &#x3D; Alternate, 5 &#x3D; EGM).
  # @option opts [Integer] :product_type The type of products to return (1 &#x3D; NoInstructions, 2 &#x3D; OnlyInstructions, 4 &#x3D; All).  This parameter has no effect when searching by category id.
  # @option opts [BOOLEAN] :web_products_only A value indicating if the response should only return products assigned to web families.
  # @return [Array<Product>]
  describe 'product_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for product_get_0
  # Gets a product with the specified id.
  # Search Types: plu (default), inventorycode, guid
  # @param id The id to lookup.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search_type The type of lookup to perform (&#39;plu&#39;, &#39;inventorycode&#39; or &#39;guid&#39;).
  # @option opts [BOOLEAN] :include_image A value indicating if the response should include the product image.
  # @option opts [String] :member_id A member id used to effect the price of the returned product/s.
  # @option opts [Integer] :member_type The type of member search to perform (0 &#x3D; Standard, 3 &#x3D; Alternate, 5 &#x3D; EGM).
  # @return [Product]
  describe 'product_get_0 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
