=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::PurchaseRequestApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PurchaseRequestApi' do
  before do
    # run before each test
    @instance = SwiftApi::PurchaseRequestApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PurchaseRequestApi' do
    it 'should create an instance of PurchaseRequestApi' do
      expect(@instance).to be_instance_of(SwiftApi::PurchaseRequestApi)
    end
  end

  # unit tests for purchase_request_post
  # Creates a purchase request in SwiftPOS back office.
  # 
  # @param purchase_request The purchase request to create.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'purchase_request_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
