=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::StocktakeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StocktakeApi' do
  before do
    # run before each test
    @instance = SwiftApi::StocktakeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StocktakeApi' do
    it 'should create an instance of StocktakeApi' do
      expect(@instance).to be_instance_of(SwiftApi::StocktakeApi)
    end
  end

  # unit tests for stocktake_post
  # Creates a stocktake record in SwiftPOS back office.
  # 
  # @param stocktake The stocktake to create.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'stocktake_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
