=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::TransactionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionApi' do
  before do
    # run before each test
    @instance = SwiftApi::TransactionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionApi' do
    it 'should create an instance of TransactionApi' do
      expect(@instance).to be_instance_of(SwiftApi::TransactionApi)
    end
  end

  # unit tests for transaction_get
  # Gets all transactions for a specified member.
  # 
  # @param id The id of the member.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :member_type The type of member search to perform (0 &#x3D; Standard, 3 &#x3D; Alternate, 5 &#x3D; EGM).
  # @option opts [String] :from The from date for member transactions in the format yyyy-MM-dd or yyyy-MM-dd HH:mm:ss.
  # @option opts [String] :to The to date for member transactions in the format yyyy-MM-dd or yyyy-MM-dd HH:mm:ss.
  # @return [Array<Transaction>]
  describe 'transaction_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for transaction_get_0
  # Gets all transactions for a specified member.
  # 
  # @param id The id of the member.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :member_type The type of member search to perform (0 &#x3D; Standard, 3 &#x3D; Alternate, 5 &#x3D; EGM).
  # @option opts [String] :from The from date for member transactions in the format yyyy-MM-dd or yyyy-MM-dd HH:mm:ss.
  # @option opts [String] :to The to date for member transactions in the format yyyy-MM-dd or yyyy-MM-dd HH:mm:ss.
  # @return [Array<Transaction>]
  describe 'transaction_get_0 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
