=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwiftApi::VoucherApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VoucherApi' do
  before do
    # run before each test
    @instance = SwiftApi::VoucherApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VoucherApi' do
    it 'should create an instance of VoucherApi' do
      expect(@instance).to be_instance_of(SwiftApi::VoucherApi)
    end
  end

  # unit tests for voucher_get
  # Gets all vouchers for a specified member.
  # 
  # @param id The id of the member.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :member_type The type of member search to perform (0 &#x3D; Standard, 3 &#x3D; Alternate, 5 &#x3D; EGM).
  # @return [Array<Voucher>]
  describe 'voucher_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for voucher_post_voucher
  # Issues a voucher to the specified member.
  # Issues a voucher to a member and supports providing a voucher mapping string for use in situations where a voucher barcode is not desired.  Please note that the barcode property is the custom voucher mapping string, which is optional.
  # @param id The id of the member.
  # @param voucher_id The id of the voucher.
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :barcode The barcode number to issue.
  # @option opts [Integer] :member_type The type of member.
  # @return [Object]
  describe 'voucher_post_voucher test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
