=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'date'

module SwiftApi
  # Defines a SwiftPOS sale.
  class SwiftPOSSale
    # Transaction Id | Int64.
    attr_accessor :id

    # Location | Complex Object.
    attr_accessor :location

    # Terminal | Complex Object.
    attr_accessor :terminal

    # Clerk | Complex Object.
    attr_accessor :clerk

    # Customer | Complex Object.
    attr_accessor :customer

    # Transaction Date | DateTime.
    attr_accessor :transaction_date

    # Transaction Type | Int16.
    attr_accessor :transaction_type

    # Table | Complex Object.
    attr_accessor :table

    # Items | Complex Object.
    attr_accessor :items

    # Media | Complex Object.
    attr_accessor :media

    # Reason for sale cancellation, refund etc | Complex Object.
    attr_accessor :reason


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'Id',
        :'location' => :'Location',
        :'terminal' => :'Terminal',
        :'clerk' => :'Clerk',
        :'customer' => :'Customer',
        :'transaction_date' => :'TransactionDate',
        :'transaction_type' => :'TransactionType',
        :'table' => :'Table',
        :'items' => :'Items',
        :'media' => :'Media',
        :'reason' => :'Reason'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'Integer',
        :'location' => :'SwiftPOSLocation',
        :'terminal' => :'SwiftPOSTerminal',
        :'clerk' => :'SwiftPOSClerk',
        :'customer' => :'SwiftPOSCustomer',
        :'transaction_date' => :'DateTime',
        :'transaction_type' => :'Integer',
        :'table' => :'SwiftPOSTable',
        :'items' => :'Array<SwiftPOSItem>',
        :'media' => :'Array<SwiftPOSMedia>',
        :'reason' => :'SwiftPOSReason'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'Id')
        self.id = attributes[:'Id']
      end

      if attributes.has_key?(:'Location')
        self.location = attributes[:'Location']
      end

      if attributes.has_key?(:'Terminal')
        self.terminal = attributes[:'Terminal']
      end

      if attributes.has_key?(:'Clerk')
        self.clerk = attributes[:'Clerk']
      end

      if attributes.has_key?(:'Customer')
        self.customer = attributes[:'Customer']
      end

      if attributes.has_key?(:'TransactionDate')
        self.transaction_date = attributes[:'TransactionDate']
      end

      if attributes.has_key?(:'TransactionType')
        self.transaction_type = attributes[:'TransactionType']
      end

      if attributes.has_key?(:'Table')
        self.table = attributes[:'Table']
      end

      if attributes.has_key?(:'Items')
        if (value = attributes[:'Items']).is_a?(Array)
          self.items = value
        end
      end

      if attributes.has_key?(:'Media')
        if (value = attributes[:'Media']).is_a?(Array)
          self.media = value
        end
      end

      if attributes.has_key?(:'Reason')
        self.reason = attributes[:'Reason']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push("invalid value for 'id', id cannot be nil.")
      end

      if @location.nil?
        invalid_properties.push("invalid value for 'location', location cannot be nil.")
      end

      if @terminal.nil?
        invalid_properties.push("invalid value for 'terminal', terminal cannot be nil.")
      end

      if @clerk.nil?
        invalid_properties.push("invalid value for 'clerk', clerk cannot be nil.")
      end

      if @customer.nil?
        invalid_properties.push("invalid value for 'customer', customer cannot be nil.")
      end

      if @transaction_date.nil?
        invalid_properties.push("invalid value for 'transaction_date', transaction_date cannot be nil.")
      end

      if @transaction_type.nil?
        invalid_properties.push("invalid value for 'transaction_type', transaction_type cannot be nil.")
      end

      if @table.nil?
        invalid_properties.push("invalid value for 'table', table cannot be nil.")
      end

      if @items.nil?
        invalid_properties.push("invalid value for 'items', items cannot be nil.")
      end

      if @media.nil?
        invalid_properties.push("invalid value for 'media', media cannot be nil.")
      end

      if @reason.nil?
        invalid_properties.push("invalid value for 'reason', reason cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @location.nil?
      return false if @terminal.nil?
      return false if @clerk.nil?
      return false if @customer.nil?
      return false if @transaction_date.nil?
      return false if @transaction_type.nil?
      return false if @table.nil?
      return false if @items.nil?
      return false if @media.nil?
      return false if @reason.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          location == o.location &&
          terminal == o.terminal &&
          clerk == o.clerk &&
          customer == o.customer &&
          transaction_date == o.transaction_date &&
          transaction_type == o.transaction_type &&
          table == o.table &&
          items == o.items &&
          media == o.media &&
          reason == o.reason
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, location, terminal, clerk, customer, transaction_date, transaction_type, table, items, media, reason].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwiftApi.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
