=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwiftApi::SwiftPOSBalance
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SwiftPOSBalance' do
  before do
    # run before each test
    @instance = SwiftApi::SwiftPOSBalance.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SwiftPOSBalance' do
    it 'should create an instance of SwiftPOSBalance' do
      expect(@instance).to be_instance_of(SwiftApi::SwiftPOSBalance)
    end
  end
  describe 'test attribute "account"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "points"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

