=begin
#SwiftPOS API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'swiftpos_api/api_client'
require 'swiftpos_api/api_error'
require 'swiftpos_api/version'
require 'swiftpos_api/configuration'

# Models
require 'swiftpos_api/models/account'
require 'swiftpos_api/models/address'
require 'swiftpos_api/models/authorisation_response'
require 'swiftpos_api/models/category'
require 'swiftpos_api/models/category_link'
require 'swiftpos_api/models/classification'
require 'swiftpos_api/models/country'
require 'swiftpos_api/models/description'
require 'swiftpos_api/models/device_license'
require 'swiftpos_api/models/error'
require 'swiftpos_api/models/family'
require 'swiftpos_api/models/group'
require 'swiftpos_api/models/issued_voucher'
require 'swiftpos_api/models/location'
require 'swiftpos_api/models/media'
require 'swiftpos_api/models/member'
require 'swiftpos_api/models/product'
require 'swiftpos_api/models/product_category'
require 'swiftpos_api/models/product_group'
require 'swiftpos_api/models/purchase_request'
require 'swiftpos_api/models/purchase_request_item'
require 'swiftpos_api/models/sale'
require 'swiftpos_api/models/sale_item'
require 'swiftpos_api/models/sale_media'
require 'swiftpos_api/models/setting'
require 'swiftpos_api/models/settings_collection'
require 'swiftpos_api/models/stocktake'
require 'swiftpos_api/models/stocktake_item'
require 'swiftpos_api/models/supplied_voucher'
require 'swiftpos_api/models/swift_pos_balance'
require 'swiftpos_api/models/swift_pos_category'
require 'swiftpos_api/models/swift_pos_classification'
require 'swiftpos_api/models/swift_pos_clerk'
require 'swiftpos_api/models/swift_pos_customer'
require 'swiftpos_api/models/swift_pos_group'
require 'swiftpos_api/models/swift_pos_item'
require 'swiftpos_api/models/swift_pos_location'
require 'swiftpos_api/models/swift_pos_master_group'
require 'swiftpos_api/models/swift_pos_media'
require 'swiftpos_api/models/swift_pos_price_level'
require 'swiftpos_api/models/swift_pos_reason'
require 'swiftpos_api/models/swift_pos_sale'
require 'swiftpos_api/models/swift_pos_size'
require 'swiftpos_api/models/swift_pos_table'
require 'swiftpos_api/models/swift_pos_terminal'
require 'swiftpos_api/models/swift_pos_venue'
require 'swiftpos_api/models/transaction'
require 'swiftpos_api/models/transaction_item'
require 'swiftpos_api/models/transaction_media'
require 'swiftpos_api/models/transfer'
require 'swiftpos_api/models/transfer_item'
require 'swiftpos_api/models/voucher'
require 'swiftpos_api/models/web_order'
require 'swiftpos_api/models/web_order_item'
require 'swiftpos_api/models/web_order_media'
require 'swiftpos_api/models/web_order_member'

# APIs
require 'swiftpos_api/api/authorisation_api'
require 'swiftpos_api/api/category_api'
require 'swiftpos_api/api/country_api'
require 'swiftpos_api/api/family_api'
require 'swiftpos_api/api/group_api'
require 'swiftpos_api/api/inventory_api'
require 'swiftpos_api/api/license_api'
require 'swiftpos_api/api/location_api'
require 'swiftpos_api/api/login_api'
require 'swiftpos_api/api/media_api'
require 'swiftpos_api/api/member_api'
require 'swiftpos_api/api/notification_api'
require 'swiftpos_api/api/order_api'
require 'swiftpos_api/api/product_api'
require 'swiftpos_api/api/purchase_request_api'
require 'swiftpos_api/api/sale_api'
require 'swiftpos_api/api/settings_api'
require 'swiftpos_api/api/stocktake_api'
require 'swiftpos_api/api/transaction_api'
require 'swiftpos_api/api/transfer_api'
require 'swiftpos_api/api/voucher_api'

module SwiftApi
  class << self
    # Customize default settings for the SDK using block.
    #   SwiftApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
